### ISSUE TITLE
Search results display behavior incorrect with multiple searches

### ISSUE THREAD

**Issue by mhnsn** [BrentHarker/byumap#49]
## Expected behavior
After performing a search that returns no results, performing a second search should show only one search results window.

## Actual behavior
A second search displays a second window, and each new search adds another.
![screenshot 2017-01-31 16 24 50](https://cloud.githubusercontent.com/assets/3672342/22488894/cf85a2ca-e7d1-11e6-8236-a8a69b39f78f.png)

## How to reproduce
Search for anything that returns no results. For example, 1060 N East Campus Drive.

**Comment by mhnsn** [comment]
PS - Enjoy my Spotify playlist.

**Comment by arzon94** [comment]
I was going to say, wow I don't know any of these bands, this guy is super hip. But I was looking at the album names. still don't recognize half of them
